#%RAML 1.0
title: API with types
version: v1
types:
  Apointment:
      properties:
        id: integer
        id_patient: integer
        id_turn_diary: integer
        coment: string
        overturned: boolean
        status_code: string
